## YAML Template.
---
Ms\OauthBundle\Entity\AuthorizationCodeProfile:
    type: entity
    table: authorization_code_profiles
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        authorizationCode:
            name: code
            type: string
            length: 128
        expirationDate:
            name: expiration_date
            type: datetimetz
        redirectionUri:
            type: text
        responseType:
            type: string
            length: 255
        state:
            type: text
    manyToOne:
        client:
            targetEntity: Client
            inversedBy: authorizationCodeProfiles
            joinColumn:
                name: client_id
                referencedColumnName: id
        resourceOwner:
            targetEntity: ResourceOwner
            inversedBy: authorizationCodeProfiles
            joinColumn:
                name: resource_owner_id
                referencedColumnName: id
    manyToMany:
        scopes:
            targetEntity: AuthorizationCodeScope
            joinTable:
                name: authorization_code_profiles_to_scopes
                joinColumns:
                    code_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    scope_id:
                        referencedColumnName: id
    oneToOne:
        accessTokenProfile:
            targetEntity: AccessTokenProfile
            mappedBy: authorizationCodeProfile