## YAML Template.
---
Ms\OauthBundle\Entity\ResourceOwner:
    type: entity
    oneToMany:
        authorizationCodeProfiles:
            targetEntity: AuthorizationCodeProfile
            mappedBy: resourceOwner
        resources:
            targetEntity: Resource
            mappedBy: owner
        resourceGroups:
            targetEntity: ResourceGroup
            mappedBy: owner