Ms\OauthBundle\Entity\Resource:
    type: entity
    table: resources
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
      title:
        type: string
        length: 255
      mimeType:
        type: string
        length: 64
      content:
        type: text
    manyToOne:
        owner:
            targetEntity: ResourceOwner
            inversedBy: resources
            joinColumn:
                name: owner_id
                referencedColumnName: id
    manyToMany:
        groups:
            targetEntity: ResourceGroup
            mappedBy: resources