## YAML Template.
---
Ms\OauthBundle\Entity\ResourceOwner:
    type: entity
    oneToMany:
        authorizationCodeProfiles:
            targetEntity: AuthorizationCodeProfile
            mappedBy: resourceOwner