## YAML Template.
---
Ms\OauthBundle\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: string
            length: 43
    fields:
        email:
            type: string
            length: 255
        password:
            type: text
        salt:
            type: text
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: discriminator
        type: smallint
    discriminatorMap:
        1: User
        2: Client
    indexes:
        app_title_INDEX:
            columns: [appTitle]
    