ms_oauth_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MsOauthBundle:Default:index }

###
# OAuth Server
##
ms_oauth_clientregistration:
    pattern: /registration/client
    defaults: { _controller: MsOauthBundle:Registration:client }
    
ms_oauth_clientdetails:
    pattern: /client/{id}
    defaults: { _controller: MsOauthBundle:Registration:clientDetails }
    requirements:
        id: ".+"
    
ms_oauth_authorization:
    pattern: /authorization
    defaults: { _controller: MsOauthBundle:Authorization:authorizationCode }
    
ms_oauth_authorization_acceptance:
    pattern: /authorization/accept
    defaults: { _controller: MsOauthBundle:Authorization:resourceOwnerAcceptance }
    
ms_oauth_authorization_access_denied:
    pattern: /authorization/access_denied
    defaults: { _controller: MsOauthBundle:Authorization:accessDenied }
    
ms_oauth_authentication_resource_owner:
    pattern: /authentication/resource_owner
    defaults: { _controller: MsOauthBundle:Authentication:resourceOwner }
    
ms_oauth_authorization_access_token:
    pattern: /authorization/access_token
    defaults: { _controller: MsOauthBundle:Authorization:accessToken }
    
ms_oauth_authentication_client_login:
    pattern: /authentication/client/login
    defaults: { _controller: MsOauthBundle:Authentication:clientLogin }
    
ms_oauth_authentication_client_login_check:
    pattern: /authentication/client/login_check
    
ms_oauth_authentication_logout:
    pattern: /authentication/logout

###
# Demos
##
ms_oauth_client_demo1:
  pattern: /client-app/demo1
  defaults: { _controller: MsOauthBundle:Client:demo1 }

###
# Utilities
##
ms_oauth_benchmark_auth:
    pattern: /benchmark/authentication
    defaults: { _controller: MsOauthBundle:Benchmark:authentication }