ms_oauth_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MsOauthBundle:Default:index }

###
# OAuth Server
##
ms_oauth_clientregistration:
    pattern: /oauth2/c/registration/
    defaults: { _controller: MsOauthBundle:Registration:client }
    
ms_oauth_clientdetails:
    pattern: /oauth2/c/client/{id}
    defaults: { _controller: MsOauthBundle:Registration:clientDetails }
    requirements:
        id: ".+"
    
ms_oauth_authorization:
    pattern: /oauth2/c/authorization
    defaults: { _controller: MsOauthBundle:Authorization:authorizationCode }
    
ms_oauth_authorization_acceptance:
    pattern: /oauth2/u/authorization/accept
    defaults: { _controller: MsOauthBundle:Authorization:resourceOwnerAcceptance }
    
ms_oauth_authorization_access_denied:
    pattern: /oauth2/c/authorization/access_denied
    defaults: { _controller: MsOauthBundle:Authorization:accessDenied }
    
#ms_oauth_authentication_resource_owner:
#    pattern: /authentication/
#    defaults: { _controller: MsOauthBundle:Authentication:resourceOwner }
    
ms_oauth_authorization_access_token:
    pattern: /oauth2/c/authorization/access_token
    defaults: { _controller: MsOauthBundle:Authorization:accessToken }
    
ms_oauth_authorization_invalid_client:
    pattern: /oauth2/c/authorization/invalid_client
    defaults: { _controller: MsOauthBundle:Authorization:invalidClient }
    
ms_oauth_authentication_client_login:
    pattern: /oauth2/c/authentication/login
    defaults: { _controller: MsOauthBundle:Authentication:clientLogin }
    
ms_oauth_authentication_client_login_check:
    pattern: /oauth2/c/authentication/login_check
    
ms_oauth_authentication_client_logout:
    pattern: /oauth2/c/authentication/logout
    
ms_oauth_authentication_client_login_failure:
    pattern: /oauth2/c/authentication/fail
    defaults: { _controller: MsOauthBundle:Authentication:clientLoginFail }

ms_oauth_registration_user:
    pattern: /oauth2/u/registration/
    defaults: { _controller: MsOauthBundle:Registration:user }
    
ms_oauth_user_details:
    pattern: /oauth2/u/user/{id}
    defaults: { _controller: MsOauthBundle:Registration:userDetails }
    
ms_oauth_authentication_user_login:
    pattern: /oauth2/u/authentication/login
    defaults: { _controller: MsOauthBundle:Authentication:login }
    
ms_oauth_authentication_user_login_check:
    pattern: /oauth2/u/authentication/login_check
    
ms_oauth_authentication_user_logout:
    pattern: /oauth2/u/authentication/logout
    
ms_oauth_access_token_validation:
    pattern: /oauth2/c/accessToken/validation/{token}
    defaults: { _controller: MsOauthBundle:Authorization:validateToken }
    requirements:
        token: ".+"

ms_oauth_access_token_info:
    pattern: /oauth2/c/tokenInfo/{token}
    defaults: { _controller: MsOauthBundle:Authorization:tokenInfo }
    requirements:
        token: ".+"

###
# Resource Server
##
ms_resource_user_profile:
    pattern: /oauth2/u/profile
    defaults: { _controller: MsOauthBundle:Resource:userProfile }

ms_resource:
    pattern: /resource/{name}
    defaults: { _controller: MsOauthBundle:Resource:resource }
    
ms_resource_image_jpg:
    pattern: /resource/image/jpg/{name}
    defaults: { _controller: MsOauthBundle:Resource:image }
    methods: [GET]
    
ms_resource_image_jpg_group:
    pattern: /resource/group/image/jpg/{name}
    defaults: { _controller: MsOauthBundle:Resource:imageGroup }
    methods: [GET]

###
# Demos
##
#ms_oauth_client_demo1:
#  pattern: /client-app/demo1
#  defaults: { _controller: MsOauthBundle:Client:demo1 }
  
ms_oauth_client_demo1_token_request_expiredGrant:
    pattern: /client-app/demo1/access_token/expiredGrant
    defaults: { _controller: MsOauthBundle:Client:demo1AccessTokenExpiredGrant }
  
ms_oauth_client_demo1_token_request_invalid_redUri:
    pattern: /client-app/demo1/access_token/invalid_redUri
    defaults: { _controller: MsOauthBundle:Client:demo1AccessTokenInvalidRedirectionUri }
  
ms_oauth_client_demo1_token_request_mrp:
    pattern: /client-app/demo1/access_token/mrp
    defaults: { _controller: MsOauthBundle:Client:demo1AccessTokenMissingRequiredParameter }

ms_oauth_client_demo1_token_request_m_redUri:
    pattern: /client-app/demo1/access_token/m_redUri
    defaults: { _controller: MsOauthBundle:Client:demo1AccessTokenMissingRedirectionUri }

ms_oauth_client_demo1_token_request_reused_grant:
    pattern: /client-app/demo1/access_token/reused_grant
    defaults: { _controller: MsOauthBundle:Client:demo1AccessTokenReusedGrant }

ms_oauth_client_demo1_token_request_unsupportedGrantType:
    pattern: /client-app/demo1/access_token/uns_grantType
    defaults: { _controller: MsOauthBundle:Client:demo1AccessTokenUnsupportedGrantType }

ms_oauth_client_demo1_token_request_wrongClientId:
    pattern: /client-app/demo1/access_token/wrongClientId
    defaults: { _controller: MsOauthBundle:Client:demo1AccessTokenWrongClientId }

###
# Utilities
##
ms_oauth_benchmark_auth:
    pattern: /benchmark/authentication
    defaults: { _controller: MsOauthBundle:Benchmark:authentication }