ms_oauth_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MsOauthBundle:Default:index }

###
# OAuth Server
##
ms_oauth_clientregistration:
    pattern: /oauth2/c/registration/
    defaults: { _controller: MsOauthBundle:Registration:client }
    
ms_oauth_clientdetails:
    pattern: /oauth2/c/client/{id}
    defaults: { _controller: MsOauthBundle:Registration:clientDetails }
    requirements:
        id: ".+"
    
ms_oauth_authorization:
    pattern: /oauth2/c/authorization
    defaults: { _controller: MsOauthBundle:Authorization:authorizationCode }
    
ms_oauth_authorization_acceptance:
    pattern: /oauth2/u/authorization/accept
    defaults: { _controller: MsOauthBundle:Authorization:resourceOwnerAcceptance }
    
ms_oauth_authorization_access_denied:
    pattern: /oauth2/c/authorization/access_denied
    defaults: { _controller: MsOauthBundle:Authorization:accessDenied }
    
#ms_oauth_authentication_resource_owner:
#    pattern: /authentication/
#    defaults: { _controller: MsOauthBundle:Authentication:resourceOwner }
    
ms_oauth_authorization_access_token:
    pattern: /oauth2/c/authorization/access_token
    defaults: { _controller: MsOauthBundle:Authorization:accessToken }
    
ms_oauth_authentication_client_login:
    pattern: /oauth2/c/authentication/login
    defaults: { _controller: MsOauthBundle:Authentication:clientLogin }
    
ms_oauth_authentication_client_login_check:
    pattern: /oauth2/c/authentication/login_check
    
ms_oauth_authentication_client_logout:
    pattern: /oauth2/c/authentication/logout
    
ms_oauth_authentication_user_login:
    pattern: /oauth2/u/authentication/login
    defaults: { _controller: MsOauthBundle:Authentication:login }
    
ms_oauth_authentication_user_login_check:
    pattern: /oauth2/u/authentication/login_check
    
ms_oauth_authentication_user_logout:
    pattern: /oauth2/u/authentication/logout

###
# Demos
##
ms_oauth_client_demo1:
  pattern: /client-app/demo1
  defaults: { _controller: MsOauthBundle:Client:demo1 }

###
# Utilities
##
ms_oauth_benchmark_auth:
    pattern: /benchmark/authentication
    defaults: { _controller: MsOauthBundle:Benchmark:authentication }