ms_oauth_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MsOauthBundle:Default:index }

ms_oauth_clientregistration:
    pattern: /registration/client
    defaults: { _controller: MsOauthBundle:Registration:client }
    
ms_oauth_clientdetails:
    pattern: /client/{id}
    defaults: { _controller: MsOauthBundle:Registration:clientDetails }
    
ms_oauth_benchmark_auth:
    pattern: /benchmark/authentication
    defaults: { _controller: MsOauthBundle:Benchmark:authentication }
    
ms_oauth_authorization:
    pattern: /authorization
    defaults: { _controller: MsOauthBundle:Authorization:authorizationCode }
    
ms_oauth_client_demo1:
  pattern: /client-app/demo1
  defaults: { _controller: MsOauthBundle:Client:demo1 }