parameters:
#    ms_oauth.example.class: Ms\OauthBundle\Example

services:
#    ms_oauth.example:
#        class: %ms_oauth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
