ms_demo_homepage:
    pattern:  /demo
    defaults: { _controller: MsDemoBundle:Client:demo1 }
    
ms_demo_resource_image:
    pattern: /demo/img/{name}
    defaults: { _controller: MsDemoBundle:Client:image}
