ms_demo_homepage:
    pattern:  /demo
    defaults: { _controller: MsDemoBundle:Client:demo1 }
    
ms_demo_resource_image:
    pattern: /demo/img/{name}
    defaults: { _controller: MsDemoBundle:Client:image }
    
ms_demo_resource_image_group:
    pattern: /demo/group/image/{name}
    defaults: { _controller: MsDemoBundle:Client:imageGroup }
