ms_demo_homepage:
    pattern:  /demo
    defaults: { _controller: MsDemoBundle:Client:demo }
    
ms_demo_app:
  pattern: /client-app/demo1
  defaults: { _controller: MsDemoBundle:Client:demo }
    
ms_demo_resource_image:
    pattern: /demo/img/{name}
    defaults: { _controller: MsDemoBundle:Client:image }
    
ms_demo_resource_image_group:
    pattern: /demo/group/image/{name}
    defaults: { _controller: MsDemoBundle:Client:imageGroup }
    
ms_demo_resource_image_group_form:
    pattern: /demo/group/image
    defaults: { _controller: MsDemoBundle:Client:imageGroup }
